trigger: none
pr: none

parameters:
- name: runtime_env
  displayName: Runtime environment
  type: string
  default: "dev"
  values:
  - dev
  - prod
- name: environment_name
  displayName: Environment name
  type: string
  default: "sample"
  values:
    - sample
- name: tag
  displayName: Custom tag
  type: string
  default: "default"

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    displayName: Build ${{parameters.runtime_env}}

    variables:
    - group: h4e-${{parameters.runtime_env}}

    jobs:
    - job: build_aml_environment
      container: condaforge/mambaforge:latest
      displayName: Build "${{parameters.runtime_env}}-${{parameters.environment_name}}-env" AML environment
      steps:
        - template: $(Build.SourcesDirectory)/.azure/devops/templates/create_conda_env.yaml
          parameters:
            env_file_location: $(Build.SourcesDirectory)/environments/infra.yaml
            env_name: infrastructure_env

        - template: $(Build.SourcesDirectory)/.azure/devops/templates/substitute_env_vars.yaml

        - script: |
            source activate infrastructure_env
            PYTHONPATH=$PYTHONPATH:. ; export PYTHONPATH ;
            TAG_ARG=""
            if [ "${{parameters.tag}}" != "default" ]; then
              TAG_ARG="--tag ${{parameters.tag}}"
            fi
            python $(Build.SourcesDirectory)/src/build_aml_environment.py \
              --runtime_env ${{parameters.runtime_env}} \
              --${{parameters.environment_name}} \
              $TAG_ARG
          displayName: Build Azure ML environment
