$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

experiment_name: sample_experiment_name
display_name: sample_job_display_name

inputs:
  parameter_1:
    type: string
  parameter_2:
    type: number
  parameter_3:
    type: number
  parameter_4:
    type: string
  parameter_5:
    type: string
  parameter_6:
    type: string
  parameter_7:
    type: string
  parameter_8:
    type: boolean
  device:
    type: string


settings:
  default_datastore: azureml:sample_datastore
  default_compute: azureml:GPU-T4-cluster  # this will be replaced by the compute parameter

jobs:
  train_deposit_parameters_dl_model:
    type: command
    component: file:../../components/sample_component/component_spec.yaml
    inputs:
      parameter_1: ${{parent.inputs.parameter_1}}
      parameter_2: ${{parent.inputs.parameter_2}}
      parameter_3: ${{parent.inputs.parameter_3}}
      parameter_4: ${{parent.inputs.parameter_3}}
      parameter_5: ${{parent.inputs.parameter_3}}
      parameter_6: ${{parent.inputs.parameter_3}}
      parameter_7: ${{parent.inputs.parameter_3}}
      parameter_8: ${{parent.inputs.parameter_3}}

      device: ${{parent.inputs.device}}

      input_dir:
        type: uri_folder
        mode: ro_mount
        path: azureml://subscriptions/<<AZ__SUBSCRIPTION_ID>>/resourcegroups/<<AZ__RESOURCE_GROUP>>/workspaces/<<AML_SETTINGS__WORKSPACE_NAME>>/datastores/<<AML_SETTINGS__STAGE_3_4_DATASTORE_NAME>>/paths/<<BLOB__H4E_STAGES_3_4_MINERALIZATION_MAPS_FOLDER_NAME>>

    outputs:
      output_dir:
        mode: rw_mount
        path: azureml://subscriptions/<<AZ__SUBSCRIPTION_ID>>/resourcegroups/<<AZ__RESOURCE_GROUP>>/workspaces/<<AML_SETTINGS__WORKSPACE_NAME>>/datastores/<<AML_SETTINGS__STAGE_3_4_DATASTORE_NAME>>/paths/<<BLOB__H4E_STAGES_3_4_DEPOSIT_PARAMETERS_FOLDER_NAME>>
