trigger: none
pr: none

parameters:
- name: runtime_env
  displayName: Runtime environment
  type: string
  default: "dev"
  values:
  - dev
  - prod
- name: environment_name
  displayName: Environment name
  type: string
  default: "sample_project"
  values:
    - "sample_project"
- name: tag
  displayName: Custom tag
  type: string
  default: "default"

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    displayName: Build ${{parameters.runtime_env}}

    variables:
    - group: h4e-${{parameters.runtime_env}}

    jobs:
    - job: build_aml_environment
      container: condaforge/mambaforge:latest
      displayName: Build "${{parameters.runtime_env}}_${{parameters.environment_name}}_env" AML environment
      steps:
        - template: ../templates/create_conda_env.yaml
          parameters:
            env_file_location: $(Build.SourcesDirectory)/environments/infrastructure.yaml
            env_name: infrastructure_env

        - template: ../templates/substitute_env_vars.yaml

        - script: |
            echo "Path to Python interpreter:"
            which python

        - script: |
            conda env list

        - script: |
            echo "PYTHONPATH: $PYTHONPATH"

        - script: |
            echo "Activating conda environment..."
            source activate infrastructure_env
            echo "Python version:"
            python --version
            echo "Installed packages:"
            python -m pip list
            PYTHONPATH=$PYTHONPATH:. ; export PYTHONPATH
            TAG=""
            if [ "${{parameters.tag}}" != "default" ]; then
              TAG="--tag ${{parameters.tag}}"
            fi
            python ./src/build_aml_environment.py \
              --runtime_env ${{parameters.runtime_env}} \
              --${{parameters.environment_name}} \
              $TAG
          displayName: Build Azure ML environment
