trigger: none
pr: none

parameters:
- name: runtime_env
  displayName: Runtime environment
  type: string
  default: "dev"
  values:
  - dev
  - prod
- name: environment_name
  displayName: Environment name
  type: string
  default: "sample-project"
  values:
    - "sample-project"
- name: accelerator
  displayName: Accelerator to use for training
  type: string
  default: "gpu"
  values:
    - "cpu"
    - "gpu"
- name: use_dedicated_compute
  displayName: Use dedicated compute for environment building (use in case of memory issues)
  type: boolean
  default: false

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    displayName: Build ${{parameters.runtime_env}}

    variables:
    - group: h4e-${{parameters.runtime_env}}

    jobs:
    - job: build_aml_environment
      container: condaforge/mambaforge:latest
      displayName: Build "${{parameters.runtime_env}}-${{parameters.environment_name}}-env" Azure ML environment
      steps:
        - template: ../templates/create-conda-env.yaml
          parameters:
            env_file_path: $(Build.SourcesDirectory)/environments/infrastructure.yaml
            env_name: infrastructure-env

        - template: ../templates/substitute-env-vars.yaml

        - script: |
            source activate infrastructure-env
            PYTHONPATH=$PYTHONPATH:. ; export PYTHONPATH ;

            USE_DEDICATED_COMPUTE=""

            if [ "$(echo ${{parameters.use_dedicated_compute}} | tr '[:upper:]' '[:lower:]')" = "true" ]; then
              USE_DEDICATED_COMPUTE="--use_dedicated_compute"
            fi

            python ./src/build_aml_environment.py \
              --runtime_env ${{parameters.runtime_env}} \
              --environment_name ${{parameters.environment_name}} \
              --accelerator ${{parameters.accelerator}} \
              $USE_DEDICATED_COMPUTE

          displayName: Build Azure ML environment
