trigger: none

pr: none

parameters:

  - name: parameter_1
    displayName: Parameter 1
    type: string
    default: "parameter-1"
  - name: parameter_2
    displayName: Parameter 2
    type: number
    default: 42
  - name: parameter_3
    displayName: Parameter 3
    type: number
    default: 0.52
  - name: parameter_4
    displayName: Parameter 4
    type: string
    default: "."
  - name: parameter_5
    displayName: Parameter 5
    type: string
    default: "parameter,_,5"
  - name: parameter_6
    displayName: Parameter 6
    type: string
    default: "1, 2,3"
  - name: parameter_7
    displayName: Parameter 7
    type: string
    default: " 0.1,0.2,3e-4"
  - name: parameter_8
    displayName: Parameter 8
    type: boolean
    default: False
  - name: parameter_9
    displayName: Parameter 9
    type: boolean
    default: True

  - name: compute
    displayName: Compute cluster to use
    type: string
    values:
      - azureml:GPU-T4-cluster
      - azureml:GPU-V100-cluster
      - azureml:CPU-DSeries-cluster
      - azureml:CPU-D14Series-cluster
    default: azureml:CPU-DSeries-cluster


variables:
- group: h4e-dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    displayName: Execute sample Azure DevOps pipeline

    jobs:
    - job: execute_pipeline
      displayName: Execute sample Azure DevOps pipeline

      steps:
        - checkout: self
          path: s/

        - template: ../templates/install_azure_cli.yaml

        - template: ../templates/configure_aml_extension.yaml

        - template: ../templates/connect_to_aml_workspace.yaml

        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          inputs:
            targetFiles: "src/sample_project/aml/pipelines/sample_pipeline/pipeline_spec.yaml"
            encoding: "auto"
            writeBOM: true
            actionOnMissing: "warn"
            keepToken: false
            tokenPrefix: "<<"
            tokenSuffix: ">>"
            useLegacyPattern: false
            enableTelemetry: true
          displayName: Substitute placeholders in pipeline_spec.yaml with environment variables

        - task: AzureCLI@2
          displayName: Run AML pipeline
          continueOnError: true
          inputs:
            azureSubscription: $(ADO__RES_MNGR_SRVC_CONN_NAME) # needs to have access at the RG level
            scriptType: bash
            workingDirectory: $(System.DefaultWorkingDirectory)
            scriptLocation: inlineScript
            inlineScript: |
              # Determine whether the compute target is CPU or GPU based and set device accordingly
              if [[ "${{parameters.compute}}" == azureml:GPU* ]]; then
                device="gpu"
              else
                device="cpu"
              fi

              # Set custom experiment ID
              timestamp=$(date +%Y-%m-%d-%H:%M:%S)
              build_id=$(Build.BuildId)
              job_id="${build_id}_${timestamp}"
              experiment_name="custom_experiment_name"

              # Create and run the pipeline
              # Remember to add quotes around the string parameters to avoid YAML parsing errors
              run_id=$( \
                az ml job create -f src/sample_project/aml/pipelines/sample_pipeline/pipeline_spec.yaml \
                --set \
                inputs.parameter_1="${{parameters.parameter_1}}" \
                inputs.parameter_2=${{parameters.parameter_2}} \
                inputs.parameter_3=${{parameters.parameter_3}} \
                inputs.parameter_4="${{parameters.parameter_4}}" \
                inputs.parameter_5="${{parameters.parameter_5}}" \
                inputs.parameter_6="${{parameters.parameter_6}}" \
                inputs.parameter_7="${{parameters.parameter_7}}" \
                inputs.parameter_8=${{parameters.parameter_8}} \
                --query name -o tsv \
                --verbose \
              )

              if [[ -z "$run_id" ]]
              then
                echo "Job creation failed"
                exit 3
              fi

              az ml job show -n $run_id --web
