data:
  dataset_dir: "path://data/dataset"  # relative to root directory (with `path://` prefix)
  batch_size: 16

preprocessing:
  name_list:
    - resize
  extra_arguments_list:
    - size: 256

model:
  name: resnet18
  pretrained: true
  num_classes: 6
  in_channels: 3

loss_function:
  name: cross_entropy_loss

optimizer:
  name: adam
  learning_rate: 0.0003

metrics:
  name_list:
    - accuracy
    - f1_score
  task: multiclass
  num_classes: 6

trainer:
  max_epochs: 50
  accelerator: gpu

callbacks:
  early_stopping:
    monitor: val_loss
    min_delta: 0.001
    patience: 10
    verbose: true
    mode: min
  model_checkpoint:
    dirpath: "path://data/checkpoints"  # relative to root directory (with `path:` prefix)
    monitor: val_loss
    filename: "{epoch}-{val_loss:.2f}"
    save_top_k: 3
    mode: min
    verbose: true
  learning_rate_monitor:
    log_momentum: true
    log_weight_decay: true

loggers:
  name_list:
    - csv
  save_dir: "path://data/logs"  # relative to root directory (with `path:` prefix)
