seed: 42

data:
  dataset_dir: "data/dataset"  # relative to root directory
  artifacts_dir: "artifacts/droplet-drug-classificator"  # relative to root directory
  val_split: 0.25
  test_split: 0.25
  batch_size: 8

preprocessing:
  name_list:
    - normalize
    - resize
  extra_arguments_list:
    - mean: [0.376, 0.428, 0.257]
      std: [0.152, 0.164, 0.149]
    - size: [256, 256]

model:
  name: resnet18
  pretrained: true
  num_classes: 6
  in_channels: 3

loss_function:
  name: cross_entropy_loss
  extra_arguments: {}

optimizer:
  name: adam
  learning_rate: 0.0003
  weight_decay: 0
  extra_arguments: {}

metrics:
  name_list:
    - accuracy
    - f1_score
    - precision
    - recall
    - jaccard_index
  task: multiclass
  num_classes: 6
  extra_arguments_list:
      - {}
      - {}
      - {}
      - {}
      - {}

callbacks:
  early_stopping:
    monitor: val_loss
    mode: min
    patience: 3
    min_delta: 0.001
    verbose: true
  model_checkpoint:
    monitor: val_loss
    mode: min
    save_top_k: 3
    filename: "{epoch}-{val_loss:.4f}"
    verbose: true
  learning_rate_monitor:
    log_momentum: true
    log_weight_decay: true
  learning_curve_logger:
    log_loss: true
    log_metrics: true
  confusion_matrix_logger:
    class_dict:
        0: "gelatin-capsule"
        1: "lactose"
        2: "methyl-cellulose"
        3: "naproxen"
        4: "pearlitol"
        5: "polyvinyl-alcohol"
    task_type: multiclass
    log_train: true
    log_val: true
    log_test: true
    normalize: true
  misclassification_logger:
    log_train: false
    log_val: true
    log_test: true
    top_n: 5

trainer:
  max_epochs: 10
  accelerator: gpu
  precision: 32
  log_every_n_steps: 50
  accumulate_grad_batches: 1  # 1 for no accumulation
  fast_dev_run: false  # set to true for debugging
  overfit_batches: 0.0  # 0.0 means no overfitting
