seed: 42

data:
  dataset_dir: "data/dataset"  # relative to root directory
  artifacts_dir: "artifacts/droplet-drug-regressor"  # relative to root directory
  val_split: 0.1
  test_split: 0.8
  batch_size: 8

preprocessing:
  name_list:
    - normalize
    - resize
  extra_arguments_list:
    - mean: 0  # [0.376, 0.428, 0.257]
      std: 1  # [0.152, 0.164, 0.149]
    - size:
      - 256
      - 256

model:
  name: resnet18
  pretrained: true
  num_classes: 1  # Use 1 for regression
  in_channels: 3

loss_function:
  name: mean_squared_error
  extra_arguments: {}

optimizer:
  name: adam
  learning_rate: 0.0003
  weight_decay: 0
  extra_arguments: {}

augmentations:
  name_list:
    - random_horizontal_flip
    - random_vertical_flip
    - random_rotation
  extra_arguments_list:
    - {}
    - {}
    - degrees: 45

callbacks:
  early_stopping:
    monitor: val_loss
    mode: min
    patience: 20
    min_delta: 0.001
    verbose: true
  model_checkpoint:
    monitor: val_loss
    mode: min
    save_top_k: 3
    filename: "{epoch}-{val_loss:.4f}"
    verbose: true
  learning_rate_monitor:
    log_momentum: true
    log_weight_decay: true
  learning_curve_logger:
    log_loss: true
    log_metrics: true

trainer:
  max_epochs: 100
  accelerator: gpu
  precision: 32
  log_every_n_steps: 50
  accumulate_grad_batches: 1  # 1 for no accumulation
  fast_dev_run: false  # set to true for debugging
  overfit_batches: 0.0  # 0.0 means no overfitting
