steps:
  - task: AzureCLI@2
    displayName: Connect to Azure ML Workspace using CLI v2
    inputs:
      azureSubscription: $(ADO__MLWS_SRVC_CONN_NAME)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az configure --defaults group=$(AML_SETTINGS__RESOURCE_GROUP) workspace=$(AML_SETTINGS__WORKSPACE_NAME)
